### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by mikaelivanov** [bonitoo-io/influxdb-connector#27]
Removed due to the reason that it was not an actual issue.

**Comment by bednar** [comment]
Hi @mikaelivanov,

thanks for using our connector.

The connector uses `Schema query` for determine available fields. Can you test the query in your InfluxDB?

https://github.com/influxdata/influxdb-gds-connector#schema-query

Regards

**Comment by mikaelivanov** [comment]
The first query:
import "influxdata/influxdb/v1"

bucket = "my-bucket"
measurement = "my-measurement"
start_range = duration(v: uint(v: 1970-01-01) - uint(v: now()))

v1.tagKeys(
  bucket: bucket,
  predicate: (r) => r._measurement == measurement,
  start: start_range
) |> filter(fn: (r) => r._value != "_start" and r._value != "_stop" and r._value != "_measurement" and r._value != "_field")
  |> yield(name: "tags")
![influxfields2ndquery](https://user-images.githubusercontent.com/45756473/201200335-d9133f04-bb64-4e96-869f-a5595657c2ad.png)


This is what I get when I run this query 
from(bucket: bucket)
  |> range(start: start_range)
  |> filter(fn: (r) => r["_measurement"] == measurement)
  |> keep(fn: (column) => column == "_field" or column == "_value")
  |> unique(column: "_field")
  |> yield(name: "fields")
![influxFields](https://user-images.githubusercontent.com/45756473/201199161-9c59694b-f445-4913-9777-101d28f856be.png)

**Comment by bednar** [comment]
Did you use `range filter` with  `start_range = duration(v: uint(v: 1970-01-01) - uint(v: now()))` value when you testing the query? 

Did you set `Schema Query Range` during the onboarding in Google Data Studio?

![image](https://user-images.githubusercontent.com/455137/201305862-d5b7af1f-3926-4c9f-8979-5163770c678b.png)

**Comment by mikaelivanov** [comment]
It's fixed

**Comment by mikaelivanov** [comment]
Hey, @bednar is it possible to delete this issue?

On the other hand, thank you for being so swift with your services, it is highly appreciated!

**Comment by bednar** [comment]
> Hey, @bednar is it possible to delete this issue?

It is not necessary. The issue is tagged as `wontfix` and closed as `not planned`.
