### ISSUE TITLE
Datasource cannot retrieve list of Buckets

### ISSUE THREAD

**Issue by felicemassaro** [bonitoo-io/influxdb-connector#28]
Hi,
I am unable to connect the datasource. The following error is generated:

`Cannot retrieve a list of Buckets. InfluxDB Error Response: "Invalid argument: xxx.119.230.43:50500/api/v2/query?org=Home"`

I did try with a new read/write token and even with a fresh organisation but cannot get it to connect.
The port 50500 has been checked and is open pointing to the VM port 8086 on the internal network

<img width="752" alt="Screenshot 2023-05-18 at 05 54 52" src="https://github.com/influxdata/influxdb-gds-connector/assets/122860105/693d1f25-69f0-42a6-a6b4-2f6a2bd4042b">

**Comment by bednar** [comment]
Hi @felicemassaro,

thanks for using our connector.

Is your InfluxDB host public? Can you call `curl -i -X GET https://xxx.119.230.43:50500/ping`?

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
