### ISSUE TITLE
InfluxDB Connector Issue

### ISSUE THREAD

**Issue by alexmc1510** [bonitoo-io/influxdb-connector#30]
Connector not available inside my company workspace. Would it be possible to share the method to install it from scratch?
I have the possibility to create a new connector so I would like to try to install it.

Thanks

**Comment by bednar** [comment]
Hi @alexmc1510,

you can use following link: https://datastudio.google.com/u/0/datasources/create?connectorId=AKfycbwhJChhmMypQvNlihgRJMAhCb8gaM3ii9oUNWlW_Cp2PbJSfqeHfPyjNVp15iy9ltCs

Best Regards
